### ISSUE TITLE
[3d] Create Category

### ISSUE THREAD

**Issue by SquatchHunter** [BedrockTweaks/Files#132]
Since we know its possible to use attachables for 3d items, we may as well make the 3d category and the following things will need to be done;
- [x] Move 3d Sun & Moon
- [ ] #47 
- [x] #46 

Do we still need to check if 3d blocks like redstone, bars, chains ect can be done? or is not possible.

**Comment by PAPISOP** [comment]
We cannot change the models of block so no, redstone, bars, chains, etc are not possible. Only items can be made 3D

**Comment by SquatchHunter** [comment]
we _can_, unsure if we can overwrite the vanilla blocks.

**Comment by MPAD2277** [comment]
"Blockshapes are essentially block geometries or models that are hard-coded into vanilla, meaning that they exist without having accessible files." - [Bedrock Wiki](https://wiki.bedrock.dev/blocks/block-shapes.html)

Which means we cant make custom blockshapes since its hard-coded. We can only use existing blockshapes

**Comment by SquatchHunter** [comment]
I have literally made custom block shapes.
also did you miss BOTH of the 2 disclaimers at the top of the page saying its no longer supported and a rework is due for like most of Bedrock Wiki
