### ISSUE TITLE
[Retro] Rename 'Pottery Sherds' to 'Pottery Shards'

### ISSUE THREAD

**Issue by PAPISOP** [BedrockTweaks/Files#193]
Unwanted files "en_au", "en_ca" and "en_nz" in texts folder in Rename 'Pottery Sherds' to 'Pottery Shards' pack

**Comment by SquatchHunter** [comment]
Vanilla Tweaks supports these languages
they are valid languages
they also have the slightest difference in spelling rules to standard UK (US is not applicable as they spell things wrong, period)

**Comment by PAPISOP** [comment]
> Vanilla Tweaks supports these languages they are valid languages they also have the slightest difference in spelling rules to standard UK (US is not applicable as they spell things wrong, period)
> 
> source: I am literally an aussie, including a AU files hurts no one but makes us happy when the UK even get stuff wrong :)

but there are only English US and English UK in bedrock, yeah they can rename those files to English US but still its doing nothing if the users dont know how to rename it (there should be same amount of languages support as java then that would have been better)

**Comment by SquatchHunter** [comment]
I read that the additional languages are supported but just not in the menu UI yet for x reason, which is why I decided that we may as well start to ship our packs with support for it out of the box so when it updates.

I went and did some reading after I made this comment to see they are not in the game, when making the comment I was sure it was already supported.
