### ISSUE TITLE
[All] Combinations

### ISSUE THREAD

**Issue by drav0011** [BedrockTweaks/Files#71]
Check if existing combinations still valid (exist in vanilla tweaks)
and add all missing combinations

**Comment by SquatchHunter** [comment]
do we have a list of packs that should be combinable, and what about packs that are totally incompatible? is there plans for a optional field in packs.json to list what is incompatible.

**Comment by PAPISOP** [comment]
You can find all the combinations used in Vanilla Tweaks in here https://vanillatweaks.net/assets/resources/resourcepacks/1.21/_hidden/

**Comment by PAPISOP** [comment]
I would suggest that in the 5.2.0 update, we will only include the changes between the packs in the combination pack as it will be easier to maintain and update packs

For example, we need to make a combination pack for hunger preview and each and every gui hunger bars, then we need to keep the entire packs in the combination, so if there is an update to hunger preview pack, then we need to also update each and every combination packs which is not great and ideal, and there can also be chances that some combinations might not receive the update due to vast amount of the combination packs @drav0011

**Comment by SquatchHunter** [comment]
some sort of symlink system would work well
